# Python for Data Analysis

McKinney, W. (2022). *Python for Data Analysis: Data Wrangling with Pandas, NumPy, and Jupyter.* O’Reilly Media.

Book Materials: https://github.com/wesm/pydata-book <br>
Machine Learning in Python: https://scikit-learn.org/stable/  <br>
Miniconda: https://docs.conda.io/en/latest/ <br>
Conda-Forge: https://conda-forge.org/ <br>

Python Libraries:
* NumPy
* pandas
* matplotlib
* SciPy
* statsmodels

Conventions:
```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm
```

It's recomended to work in other conda's environment. Using alternative environments make it easier to debug problems and ensure the stability of (base) env. Also, It's recommended the use of **miniforge** instead of Anaconda, that reduces chances of conflicting installations.

Conda commands:
- `conda env list`
- `conda create --name environment_name`
- `conda create --name my_env python=3.8`
- `conda activate environment_name`
- `conda deactivate`
- `conda install <package>`

## Index
* [NumPy Bascs: Arrays and Vectorized Computation](#numpy-bascs-arrays-and-vectorized-computation)
* [Data Types for ndarrays](#data-types-for-ndarrays)
* []


## NumPy Bascs: Arrays and Vectorized Computation

NumPy arrays use much less memory than bult-in Python sequences. Also, NumPy operations are faster than regular Python code.

### NumPy ndarray: Multidimensional Array Object

In [7]:
import numpy as np

data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

# You can operate with the values inside the array
data 
print(data*10) 
print(data+data) 

# Checknig 'data' shape and dtype 
print(data.shape) 
print(data.dtype) 


[[ 15.  -1.  30.]
 [  0. -30.  65.]]
[[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]
(2, 3)
float64


In [17]:
"""
The array function accepts any sequence-like object.
numpy.array tries to infer a good data type for the array.
"""
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)

# Creating an array 2x4 
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
print(arr2)
print(f"The shape is {arr2.shape}")

# Checking data type
print(f"\nThe data-type of Array1 is {arr1.dtype}")
print(f"The data-type of Array2 is {arr2.dtype}")

# Creating arrays full of ones
print(f"\nArray with 13 'ones': \n{np.ones(13)}")
print(f"Array 3x7 full of 'ones': \n{np.ones((3,7))}")

# Creating new array but empty
print(f"\nArray 3x4x2 empty: \n{np.empty((3,2,2))}")

# Creating a range list array (not list(range(15)) )
print(f"\nArray list of 15 numbers: \n{np.arange(15)}")

[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]
The shape is (2, 4)

The data-type of Array1 is float64
The data-type of Array2 is int32

Array with 13 'ones': 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array 3x7 full of 'ones': 
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]

Array 3x4x2 empty: 
[[[9.86556544e-312 3.16202013e-322]
  [0.00000000e+000 0.00000000e+000]]

 [[1.42413554e-306 3.40712186e+175]
  [7.56676808e-067 8.07452209e+169]]

 [[2.61795352e+180 5.50198861e+170]
  [3.29406006e-032 1.29255815e+161]]]

Array list of 15 numbers: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


*Some important NumPy array creation functions (McKinney, 2022):*
|Function    |Description|
|:-----------|:----------|
|array| Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default|
|asarray| Convert input to ndarray, but do not copy if the input is already an ndarray|
|arange| Like the built-in range but returns an ndarray instead of a list|
|ones, ones_like|Produce an array of all 1s with the given shape and data type; ones_like takes another array and produces a ones array of the same shape and data type|
|zeros, zeros_like|Like ones and ones_like but producing arrays of 0s instead|
|empty, empty_like|Create new arrays by allocating new memory, but do not populate with any values like ones and zeros|
|full, full_like|Produce an array of the given shape and data type with all values set to the indicated “fill value”; full_like takes another array and produces a filled array of the same shape and data type|
|eye, identity |Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)|

#### Data types for ndarrays

In [24]:
# Creating arrays and specifying Data type
arr1 = np.array([1.11, 2.22, 3.33], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(f"Array1 ({arr1}) data type: {arr1.dtype}")
print(f"Array2 ({arr2}) data type: {arr2.dtype}")

# Converting or 'casting' an array from one data tpe to another
flo_arr2 = arr2.astype(np.float64)
int_arr1 = arr1.astype(np.int64)
print(f"\nNow array2 ({flo_arr2}) data type's: {flo_arr2.dtype}")
print(f"Previous ({arr1}) with data type '{int_arr1.dtype}' " 
      f"now is '{int_arr1}', the decimal part has been truncated")

# Numeric string to it's correct numeric form 
num_srt = ["12.2", "13.3", "14"]
int_array = np.arange(10)

arr_num_srt = np.array(num_srt)
arr_num_flo = arr_num_srt.astype(float)

## Taking other array as dtype
arr_num_int = arr_num_flo.astype(int_array.dtype)


print(f"\nThe array '{arr_num_srt}' is '{arr_num_srt.dtype}' "
      f"\nbut we can convert it to '{arr_num_flo} wich is '{arr_num_flo.dtype}"
      f".\nAnd we can use Data type of '{int_array}' ({int_array.dtype}) to "
      f"convert in '{arr_num_int.dtype}' our '{arr_num_int}'.")



Array1 ([1.11 2.22 3.33]) data type: float64
Array2 ([1 2 3]) data type: int32

Now array2 ([1. 2. 3.]) data type's: float64
Previous ([1.11 2.22 3.33]) with data type 'int64' now is '[1 2 3]', the decimal part has been truncated

The array '['12.2' '13.3' '14']' is '<U4' 
but we can convert it to '[12.2 13.3 14. ] wich is 'float64.
And we can use Data type of '[0 1 2 3 4 5 6 7 8 9]' (int32) to convert in 'int32' our '[12 13 14]'.


*NumPy data types (McKinney, 2022):*
|Type|Type code|Description|
|:----|:------:|:---|
|int8, unit8  |  i1, u1  |Signed and unsigned 8-bit (1 byte) integer types|
|int16, uint16  |  i2, u2  | Signed and unsigned 16-bit integer types|
|int32, uint32  |  i4, u4  | Signed and unsigned 32-bit integer types|
|int64, uint64  |  i8, u8  | Signed and unsigned 64-bit integer types|
|float16  |  f2  | Half-precision floating point|
|float32  |  f4 or f  | Standard single-precision floating point; compatible with C float|
|float64  |  f8 or d  | Standard double-precision floating point; compatible with C double and Python float object|
|float128  |  f16 or g  | Extended-precision floating point|
|complex64,  <br> complex128,  <br> complex256  |  c8, c16, c32  | Complex numbers represented by two 32, 64, or 128 floats, respectively|
|bool  |  ?  | Boolean type storing True and False values|
|object  |  O  | Python object type; a value can be any Python objec|
|string_  |  S  |Fixed-length ASCII string type (1 byte per character); for example, to create a string data type with length 10, use 'S10'|
|unicode_  |  U  |Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_ (e.g., 'U10')|


#### Arithmetic with Numpy Arrays

We can do operations in Arrays without *for* loops, NumPy call this *vectorization*.

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

print(f"Array * Array: \n{arr*arr}")
print(f"Array - Array: \n{arr-arr}")
print(f"Array ^2: \n{arr**2}")

# You can compare arrays getting booleans as a result
arr2 = np.array([[0,5,2], [1, 9,7]])

print(f"\nIs Array2 greater than Array1?: \n{arr2 > arr}")

Array * Array: 
[[ 1.  4.  9.]
 [16. 25. 36.]]
Array - Array: 
[[0. 0. 0.]
 [0. 0. 0.]]
Array ^2: 
[[ 1.  4.  9.]
 [16. 25. 36.]]

Is Array2 greater than Array1?: 
[[False  True False]
 [False  True  True]]


#### Basic Indexing and Slicing

Distinction from Python lists: In Arrays, the data is not copied, then any 
modifications to the view will be reflected, even if it is an Slice.

But, you can copy the Slice if you specified that: `arr[5:8].copy()`

In [7]:
# One dimensional Arrays
import numpy as np
arr1 = np.arange(12)

print(arr1)

print(f"\nItem 5: {arr1[5]}")
print(f"Items 5 to 8: {arr1[5:8]}")

arr1[5:8] = 13

print(f"We've changed items 5 to 8: {arr1[5:8]}")
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

Item 5: 5
Items 5 to 8: [5 6 7]
We've changed items 5 to 8: [13 13 13]
[ 0  1  2  3  4 13 13 13  8  9 10 11]


In [11]:
# Slicing
import numpy as np
arr1 = np.arange(12)
print(arr1)

slice1 = arr1[5:8]
print(f"Here the slice 5 to 8: \n{slice1}")
print(f"First index from slice: {slice1[1]}")

# We only change the Slice but affect to the Array
slice1[2] = 12398
print(f"\nAfter changing the index 2 from slice, "
      f"\nThis is the complete slice: {slice1}"
      f"And this is the array: \n{arr1}")


[ 0  1  2  3  4  5  6  7  8  9 10 11]
Here the slice 5 to 8: 
[5 6 7]
First index from slice: 6
After changing the index 2 from slice, 
This is the complete slice: [    5     6 12398]And this is the array: 
[    0     1     2     3     4     5     6 12398     8     9    10    11]


In [14]:
# Bidimensional Array

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"2D Array: \n{arr2d}")
print(f"2D Array, index 2: '{arr2d[2]}'")
print(f"2D Array, index 2 and inside, index 2: '{arr2d[2, 2]}'")

arr3d = np.array([[[11,22,33], [44,55,66]], [[77,88,99], [10.,11.,12.]]])
print(f"\n3D Array: \n{arr3d}")
print(f"\n3D Array, first section (index 0): \n{arr3d[0]}"
      "\nNow, it is a 2D array too, we can work easiest this way")

2D Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2D Array, index 2: '[7 8 9]'
2D Array, index 2 and inside, index 2: '9'

3D Array: 
[[[11. 22. 33.]
  [44. 55. 66.]]

 [[77. 88. 99.]
  [10. 11. 12.]]]

3D Array, first section (index 0): 
[[11. 22. 33.]
 [44. 55. 66.]]
Now, it is a 2D array too, we can work easiest this way


##### Indexing with slices

In [17]:
arr1 = np.arange(12)
print(f"One dimensional array: \n'{arr1}'")
print(f"Selecting indexes 2 to 7: '{arr1[2:7]}")

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"\n2D Array: \n{arr2d}")
print(f"\nSelecting the first two rows with [:2]: \n{arr2d[:2]}")
print(f"\nNow, selecting [:2, 1:] and maintaining the same dimensions:"
      f"\n{arr2d[:2, 1:]}")
print(f"\nAnd only one 'column' with [:, :1]: \n{arr2d[:, :1]}")

One dimensional array: 
'[ 0  1  2  3  4  5  6  7  8  9 10 11]'
Selecting indexes 2 to 7: '[2 3 4 5 6]

2D Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Selecting the first two rows with [:2]: 
[[1 2 3]
 [4 5 6]]

Now, selecting [:2, 1:] and maintaining the same dimensions:
[[2 3]
 [5 6]]

And only one 'column' with [:, :1]: 
[[1]
 [4]
 [7]]


#### Boolean Indexing

In [8]:
# We'll have names and its data
import numpy as np

names = np.array(["Sue", "Lily", "Emma", "Sue", "Lily", "Emma", "Emma"])

data = np.array([[4, -7], [3, 2], [5, -9], [-2, 0], [2,6], [1,3], [-6, 8]])

print(f"This is names' variable: \n{names}")
print(f"\nAnd we are looking for Sue with =='Sue': \n{names == 'Sue'}")

# Which data corresponds with each name
print(f"\nThe data corresponding Emma 'data[names==Emma]'"
        f"is: \n{data[names=='Emma']}")
print(f"And her index 1 of data is: '{data[names=='Emma', 1]}'")

# Negative search
print(f"\nWhich names are not Lily: {names != 'Lily'}")
print(f"\nAnd not Lily's data: \n{data[~(names == 'Lily')]}")

# Selecting various name with '&' (and) and '|' (or)
some = (names == "Lily") | (names == "Sue")
print(f"Names Lily or Sue: '{some}'")

print(f"Data not Sue and greater than 6: \n{data[names != "Sue"] = 6}")

This is names' variable: 
['Sue' 'Lily' 'Emma' 'Sue' 'Lily' 'Emma' 'Emma']

And we are looking for Sue with =='Sue': 
[ True False False  True False False False]

The data corresponding Emma 'data[names==Emma]'is: 
[[ 5 -9]
 [ 1  3]
 [-6  8]]
And her index 1 of data is: '[-9  3  8]'

Which names are not Lily: [ True False  True  True False  True  True]

And not Lily's data: 
[[ 4 -7]
 [ 5 -9]
 [-2  0]
 [ 1  3]
 [-6  8]]


In [11]:
import numpy as np

arr = np.zeros((8, 4))

for i in range(8):
    arr[i] = i

print(f"\n{arr}")
print(f"\nArray1, 4-3-0-6 indexes: \n{arr[[4, 3, 0, 6]]}")

arr2 = np.arange(45).reshape((9,5))

print(f"\n{arr2}")

print(f"\nArray2 greater than 24{arr2 > 24}")


[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]

Array1, 4-3-0-6 indexes: 
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]

Array2 greater than 24[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


#### Transposing Arrays and Swapping Axes